# Generated by Django 4.0.4 on 2022-04-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type_alter_subject_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1),
        ),
    ]
